/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionSearchRequest {
    #[serde(rename = "subject")]
    pub subject: Box<models::Subject>,
    #[serde(rename = "resource")]
    pub resource: Box<models::Resource>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageRequest>>,
}

impl ActionSearchRequest {
    pub fn new(subject: models::Subject, resource: models::Resource) -> ActionSearchRequest {
        ActionSearchRequest {
            subject: Box::new(subject),
            resource: Box::new(resource),
            context: None,
            page: None,
        }
    }
}
