/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvaluationsOptions {
    #[serde(rename = "evaluations_semantic", skip_serializing_if = "Option::is_none")]
    pub evaluations_semantic: Option<models::EvaluationsSemantic>,
}

impl EvaluationsOptions {
    pub fn new() -> EvaluationsOptions {
        EvaluationsOptions {
            evaluations_semantic: None,
        }
    }
}

