/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvaluationsRequest {
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<models::Subject>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::Action>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<models::Resource>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    /// Optional. If omitted or empty, behaves like a single Access Evaluation request.
    #[serde(rename = "evaluations", skip_serializing_if = "Option::is_none")]
    pub evaluations: Option<Vec<models::EvaluationsItemRequest>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<models::EvaluationsOptions>,
}

impl EvaluationsRequest {
    pub fn new() -> EvaluationsRequest {
        EvaluationsRequest {
            subject: None,
            action: None,
            resource: None,
            context: None,
            evaluations: None,
            options: None,
        }
    }
}
