/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvaluationsItemRequest {
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<models::Subject>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<models::Resource>,
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<models::Action>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
}

impl EvaluationsItemRequest {
    pub fn new() -> EvaluationsItemRequest {
        EvaluationsItemRequest {
            subject: None,
            resource: None,
            action: None,
            context: None,
        }
    }
}
