/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectFilter {
    #[serde(rename = "type")]
    pub r#type: String,
    /// Optional subject id. If present in Subject Search, it is ignored per AuthZEN spec.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
}

impl SubjectFilter {
    pub fn new(r#type: String) -> SubjectFilter {
        SubjectFilter {
            r#type,
            id: None,
            properties: None,
        }
    }
}

