/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectSearchRequest {
    #[serde(rename = "resource")]
    pub resource: Box<models::Resource>,
    #[serde(rename = "action")]
    pub action: Box<models::Action>,
    #[serde(rename = "subject")]
    pub subject: Box<models::SubjectFilter>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<serde_json::Value>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageRequest>>,
}

impl SubjectSearchRequest {
    pub fn new(
        resource: models::Resource,
        action: models::Action,
        subject: models::SubjectFilter,
    ) -> SubjectSearchRequest {
        SubjectSearchRequest {
            resource: Box::new(resource),
            action: Box::new(action),
            subject: Box::new(subject),
            context: None,
            page: None,
        }
    }
}
