/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubjectSearchResponse {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::Subject>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::PageResponse>,
}

impl SubjectSearchResponse {
    pub fn new() -> SubjectSearchResponse {
        SubjectSearchResponse {
            results: None,
            page: None,
        }
    }
}
