/*
 * OpenFGA
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TupleToUserset {
    #[serde(rename = "tupleset")]
    pub tupleset: models::ObjectRelation,
    #[serde(rename = "computedUserset")]
    pub computed_userset: models::ObjectRelation,
}

impl V1TupleToUserset {
    pub fn new(
        tupleset: models::ObjectRelation,
        computed_userset: models::ObjectRelation,
    ) -> V1TupleToUserset {
        V1TupleToUserset {
            tupleset,
            computed_userset,
        }
    }
}
